### ISSUE TITLE
apt update error

### ISSUE THREAD

**Issue by zg9uagfv** [figozhang/runninglinuxkernel_5.0#17]
`
benshushu:benshushu# apt update

Get:1 http://mirrors.ustc.edu.cn/debian unstable InRelease [158 kB]
Err:1 http://mirrors.ustc.edu.cn/debian unstable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Reading package lists... Done
W: GPG error: http://mirrors.ustc.edu.cn/debian unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
E: The repository 'http://mirrors.ustc.edu.cn/debian unstable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by runninglinuxkernel** [comment]
请看 配套的 实验指导手册，附录。 下载方法：关注“奔跑吧linux社区”微信公众号，输入“奔跑吧2”获取下载地址

**Comment by runninglinuxkernel** [comment]
或者参考这个：

https://github.com/runninglinuxkernel/runninglinuxkernel_5.0/commit/626c3cac3130afd3239c9a7475d5df278cafa3cd
